directories:
  download: /glade/derecho/scratch/kheyblom/data/imerg_tiny/
  logs: ./logs
log_file: imerg_download_tiny.log
n_processes: 2
version: V07
products:
  - final/daily
year_range: [2025, 2025]
retries: 3
